'use strict';
const $=id=>document.getElementById(id);let pdf,bytes,filename,pages=[],current=0,tool='text',history=[],drawing=null,renderId=0,locked=false;
const overlay=$('overlay'),ctx=overlay.getContext('2d');const hints={text:'พิมพ์ข้อความ แล้วคลิกตำแหน่งบนหน้า PDF',highlight:'ลากบนหน้า PDF เพื่อไฮไลต์',pen:'ลากเพื่อวาดหรือเซ็นชื่อบนหน้า PDF',whiteout:'ลากเพื่อปิดทับ • ข้อมูลเดิมยังอยู่ ไม่ใช่การลบข้อมูลลับ'};
function status(s){$('status').textContent=s}function busy(v,s){locked=v;$('busy').hidden=!v;if(s)$('busy').textContent=s;$('download').disabled=v||!pages.length}function checkpoint(){history.push(JSON.stringify({pages,current}));if(history.length>40)history.shift();$('undo').disabled=false}function sync(){ $('count').textContent=pages.length;$('meta').textContent=pages.length?`${pages.length} หน้า · เพิ่มข้อความและเครื่องหมายบนเอกสาร`: 'เริ่มต้นด้วยการเปิดไฟล์ PDF';$('up').disabled=current===0;$('down').disabled=current===pages.length-1;$('remove').disabled=pages.length<2;$('download').disabled=locked||!pages.length;$('undo').disabled=!history.length;document.querySelectorAll('.thumb').forEach((b,i)=>b.classList.toggle('active',i===current))}
function paint(c,ops){c.clearRect(0,0,c.canvas.width,c.canvas.height);for(const a of ops){c.save();c.strokeStyle=a.color;c.fillStyle=a.color;c.lineCap='round';c.lineJoin='round';if(a.type==='text'){c.font=`${a.size}px Tahoma, sans-serif`;c.textBaseline='top';a.text.split('\n').forEach((t,i)=>c.fillText(t,a.x,a.y+i*a.size*1.4))}else if(a.type==='pen'){c.lineWidth=Math.max(1,a.size/8);c.beginPath();a.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke()}else{c.globalAlpha=a.type==='highlight'?.28:1;c.fillStyle=a.type==='whiteout'?'#ffffff':a.color;c.fillRect(a.x,a.y,a.w,a.h)}c.restore()}}
async function showPage(){if(!pdf||!pages.length)return;const rid=++renderId;const item=pages[current];const p=await pdf.getPage(item.source+1);const viewport=p.getViewport({scale:1.5});const temp=document.createElement('canvas');temp.width=viewport.width;temp.height=viewport.height;await p.render({canvasContext:temp.getContext('2d'),viewport}).promise;if(rid!==renderId)return;$('page').width=overlay.width=temp.width;$('page').height=overlay.height=temp.height;$('page').getContext('2d').drawImage(temp,0,0);$('pagewrap').style.width=temp.width+'px';paint(ctx,item.ops);sync();status(`หน้า ${current+1} จาก ${pages.length} · ${hints[tool]}`)}
async function thumbnails(){const list=$('pagelist');list.replaceChildren();for(let i=0;i<pages.length;i++){const b=document.createElement('button');b.className='thumb';b.setAttribute('aria-label',`ไปหน้า ${i+1}`);const c=document.createElement('canvas'),label=document.createElement('span');label.textContent=`หน้า ${i+1}`;b.append(c,label);b.onclick=()=>{if(locked)return;current=i;showPage().catch(fail)};list.append(b);const p=await pdf.getPage(pages[i].source+1),v=p.getViewport({scale:.2});c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise}sync()}
function fail(e){console.error(e);status('ไม่สามารถดำเนินการได้ โปรดลองใหม่');busy(false)}
async function openFile(f){if(!f||locked)return;if(f.size>50*1024*1024){status('ไฟล์ใหญ่เกิน 50 MB กรุณาเลือกไฟล์ขนาดเล็กลง');return}if(!/\.pdf$/i.test(f.name)&&f.type!=='application/pdf'){status('กรุณาเลือกไฟล์ PDF');return}if(pages.some(p=>p.ops.length)&&!confirm('เปิดไฟล์ใหม่และทิ้งการแก้ไขที่ยังไม่ได้ดาวน์โหลดหรือไม่?'))return;busy(true,'กำลังเปิดไฟล์ PDF…');try{if(!window.pdfjsLib||!window.PDFLib)throw Error('libraries');pdfjsLib.GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js';const data=new Uint8Array(await f.arrayBuffer());const doc=await pdfjsLib.getDocument({data:data.slice(),isEvalSupported:false}).promise;const check=await PDFLib.PDFDocument.load(data);if(check.isEncrypted)throw Error('encrypted');pdf=doc;bytes=data;filename=f.name;pages=Array.from({length:doc.numPages},(_,source)=>({source,ops:[]}));current=0;history=[];$('filename').textContent=filename;$('empty').hidden=true;$('pagewrap').hidden=false;$('pageactions').hidden=false;await showPage();await thumbnails();status('เปิดไฟล์แล้ว เลือกเครื่องมือเพื่อเริ่มแก้ไข')}catch(e){console.error(e);status(e.name==='PasswordException'||/encrypt/i.test(e.message)?'ไฟล์มีรหัสผ่าน กรุณาปลดล็อกไฟล์ก่อนเปิด':'เปิดไฟล์ไม่ได้ กรุณาตรวจสอบไฟล์ PDF หรือการเชื่อมต่ออินเทอร์เน็ต')}finally{busy(false);sync();$('file').value=''}}
$('open').onclick=$('choose').onclick=()=>$('file').click();$('file').onchange=e=>openFile(e.target.files[0]);['dragenter','dragover'].forEach(n=>$('workspace').addEventListener(n,e=>{e.preventDefault();$('workspace').classList.add('drag')}));$('workspace').ondragleave=()=>$('workspace').classList.remove('drag');$('workspace').ondrop=e=>{e.preventDefault();$('workspace').classList.remove('drag');openFile(e.dataTransfer.files[0])};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));$('hint').textContent=hints[tool];if(tool==='highlight')$('color').value='#ffcf24';if(tool==='text'||tool==='pen')$('color').value='#2452dd';status(hints[tool])});$('size').oninput=()=>$('sizeout').value=$('size').value;
function point(e){const r=overlay.getBoundingClientRect();return{x:(e.clientX-r.left)*overlay.width/r.width,y:(e.clientY-r.top)*overlay.height/r.height}}
overlay.onpointerdown=e=>{if(locked||!pages.length)return;const p=point(e),size=+$('size').value*1.5,color=$('color').value;if(tool==='text'){const text=$('text').value;if(!text.trim()){status('พิมพ์ข้อความในช่องด้านซ้ายก่อน');$('text').focus();return}checkpoint();pages[current].ops.push({type:tool,...p,text,size,color});paint(ctx,pages[current].ops);return}overlay.setPointerCapture(e.pointerId);drawing={type:tool,...p,w:0,h:0,size,color,points:[p]}};
overlay.onpointermove=e=>{if(!drawing)return;const p=point(e);drawing.w=p.x-drawing.x;drawing.h=p.y-drawing.y;drawing.points.push(p);paint(ctx,[...pages[current].ops,drawing])};overlay.onpointerup=()=>{if(!drawing)return;const a=drawing;drawing=null;if(a.type==='pen'?a.points.length>1:Math.abs(a.w)>2&&Math.abs(a.h)>2){checkpoint();pages[current].ops.push(a)}paint(ctx,pages[current].ops)};overlay.onpointercancel=()=>{drawing=null;paint(ctx,pages[current].ops)};
$('undo').onclick=async()=>{if(locked||!history.length)return;const s=JSON.parse(history.pop());pages=s.pages;current=s.current;busy(true,'กำลังเลิกทำ…');try{await showPage();await thumbnails()}catch(e){fail(e)}finally{busy(false);sync()}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('undo').click()}});
async function move(delta){if(locked||current+delta<0||current+delta>=pages.length)return;checkpoint();[pages[current],pages[current+delta]]=[pages[current+delta],pages[current]];current+=delta;busy(true,'กำลังจัดเรียงหน้า…');try{await showPage();await thumbnails()}catch(e){fail(e)}finally{busy(false);sync()}}$('up').onclick=()=>move(-1);$('down').onclick=()=>move(1);$('remove').onclick=async()=>{if(locked||pages.length<2)return;if(!confirm(`ลบหน้า ${current+1} หรือไม่? คุณสามารถเลิกทำได้`))return;checkpoint();pages.splice(current,1);current=Math.min(current,pages.length-1);busy(true,'กำลังลบหน้า…');try{await showPage();await thumbnails()}catch(e){fail(e)}finally{busy(false);sync()}};
$('download').onclick=async()=>{if(locked||!pages.length)return;busy(true,'กำลังสร้างไฟล์ PDF…');try{const {PDFDocument,degrees}=PDFLib;const src=await PDFDocument.load(bytes),out=await PDFDocument.create();for(const item of pages){const [p]=await out.copyPages(src,[item.source]);out.addPage(p);if(item.ops.length){const view=await pdf.getPage(item.source+1),v=view.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;paint(c.getContext('2d'),item.ops);const img=await out.embedPng(c.toDataURL('image/png'));const box=p.getCropBox();const r=((p.getRotation().angle%360)+360)%360;const positions={0:{x:box.x,y:box.y,width:box.width,height:box.height},90:{x:box.x+box.width,y:box.y,width:box.height,height:box.width},180:{x:box.x+box.width,y:box.y+box.height,width:box.width,height:box.height},270:{x:box.x,y:box.y+box.height,width:box.height,height:box.width}};p.drawImage(img,{...positions[r],rotate:degrees(r)})}}const data=await out.save();const url=URL.createObjectURL(new Blob([data],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=filename.replace(/\.pdf$/i,'')+'-edited.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('ดาวน์โหลดไฟล์ที่แก้ไขแล้วเรียบร้อย')}catch(e){console.error(e);status('สร้างไฟล์ไม่สำเร็จ กรุณาลองใหม่หรือเลือกไฟล์อื่น')}finally{busy(false)}};
window.addEventListener('beforeunload',e=>{if(history.length){e.preventDefault();e.returnValue=''}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_pdf_editor_state',description:'Read the open document page count, selected page and annotation count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('Expected empty object');return{filename:filename||null,pageCount:pages.length,selectedPage:pages.length?current+1:null,annotationCount:pages.reduce((n,p)=>n+p.ops.length,0)}}})).catch(console.error)}catch(e){console.error(e)}}
