'use strict';
const signatureImages=new Map();let signatureId=null;
hints.image='เลือกรูปลายเซ็น แล้วคลิกบน PDF เพื่อวาง • เลิกทำได้';
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{$('signatureControls').hidden=b.dataset.tool!=='image'}));
$('signatureWidth').oninput=()=>$('signatureWidthValue').value=$('signatureWidth').value;
$('signatureFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg'].includes(f.type)||f.size>10*1024*1024){status('เลือกรูป PNG / JPG ขนาดไม่เกิน 10 MB');return}const url=URL.createObjectURL(f);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>24e6)throw Error('ภาพใหญ่เกินไป กรุณาลดความละเอียด');const c=document.createElement('canvas');const scale=Math.min(1,1800/img.naturalWidth,1800/img.naturalHeight);c.width=img.naturalWidth*scale;c.height=img.naturalHeight*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);const clean=new Image();clean.src=c.toDataURL('image/png');await clean.decode();signatureId=crypto.randomUUID();signatureImages.set(signatureId,clean);$('signaturePreview').src=clean.src;$('signaturePreview').hidden=false;status('พร้อมวางลายเซ็น คลิกตำแหน่งบนเอกสาร')}catch(e){status(e.message||'เปิดรูปไม่ได้')}finally{URL.revokeObjectURL(url)}};
function placeSignature(p){const image=signatureImages.get(signatureId);if(!image){status('กรุณาเลือกรูปลายเซ็นก่อน');$('signatureFile').click();return}let w=+$('signatureWidth').value*1.5,h=w*image.height/image.width;const k=Math.min(1,overlay.width/w,overlay.height/h);w*=k;h*=k;checkpoint();pages[current].ops.push({type:'image',imageId:signatureId,x:Math.max(0,Math.min(p.x,overlay.width-w)),y:Math.max(0,Math.min(p.y,overlay.height-h)),w,h});paint(ctx,pages[current].ops);status('วางภาพลายเซ็นแล้ว • กดเลิกทำเพื่อย้ายตำแหน่ง')}
function configureCompression(){const update=()=>{const preserve=opt('mode')==='preserve';for(const id of ['resolution','quality']){const el=$('opt-'+id);el.disabled=preserve;el.hidden=preserve;document.querySelector(`label[for="opt-${id}"]`).hidden=preserve}$('toolNotice').textContent=preserve?'บีบอัดโครงสร้าง PDF โดยไม่แปลงหน้าเป็นภาพ ข้อความ รูป และช่องฟอร์มคงเดิม ไม่ลดความละเอียดของรูป บางไฟล์อาจย่อไม่ได้อีก และจะส่งคืนไฟล์เดิม':'แปลงทุกหน้าเป็นภาพ ข้อความจะเลือกหรือค้นหาไม่ได้ ลิงก์และฟอร์มจะหายไป บางไฟล์อาจใหญ่ขึ้น'};$('opt-mode').onchange=update;update()}
const formDialog=document.createElement('dialog');formDialog.id='formDialog';formDialog.innerHTML='<form method="dialog"><button class="close-dialog" aria-label="ปิด">×</button></form><span class="eyebrow">PDF STUDIO / FORMS</span><h2>กรอกฟอร์ม PDF</h2><p>รองรับช่องข้อความภาษาไทย ช่องติ๊ก และรายการตัวเลือกในฟอร์มมาตรฐาน AcroForm</p><label class="upload-zone" for="formFile">＋ เลือก PDF ที่มีช่องกรอก</label><input type="file" id="formFile" accept="application/pdf,.pdf" hidden><p id="formStatus" role="status" aria-live="polite"></p><div id="formFields"></div><div id="formResults"></div><button id="saveForm" class="primary" disabled>บันทึกและดาวน์โหลด PDF</button>';
document.body.append(formDialog);let formData=null,formName='',formEntries=[],formWorking=false,formUrls=[];
function openFormTool(){formDialog.showModal()}
formDialog.addEventListener('cancel',e=>{if(formWorking)e.preventDefault()});formDialog.querySelector('form').onsubmit=e=>{if(formWorking)e.preventDefault()};
function lockForm(on){formWorking=on;$('formFile').disabled=on;formDialog.querySelector('.close-dialog').disabled=on;$('saveForm').disabled=on||!formEntries.some(e=>!e.readOnly);for(const e of formEntries)e.control.disabled=on||e.readOnly}
$('formFile').onchange=async e=>{const f=e.target.files[0];if(!f||formWorking)return;formData=null;formEntries=[];$('formFields').replaceChildren();$('formResults').replaceChildren();for(const url of formUrls)URL.revokeObjectURL(url);formUrls=[];lockForm(true);try{if(f.size>50*1024*1024)throw Error('ไฟล์ใหญ่เกิน 50 MB');$('formStatus').textContent='กำลังอ่านช่องฟอร์ม…';const data=new Uint8Array(await f.arrayBuffer());const doc=await PDFLib.PDFDocument.load(data,{updateMetadata:false});const form=doc.getForm();if(form.hasXFA())throw Error('ยังไม่รองรับฟอร์ม XFA กรุณาใช้ฟอร์ม AcroForm');const fields=form.getFields();let unsupported=0;fields.forEach((field,index)=>{const kind=PDFFeatures.fieldKind(field,PDFLib);if(kind==='unsupported'){unsupported++;return}const row=document.createElement('div');row.className='form-row';const label=document.createElement('label');label.htmlFor='fill-'+index;label.textContent=field.getName()+(field.isRequired()?' *':'')+(field.isReadOnly()?' (อ่านอย่างเดียว)':'');let control;
if(kind==='text'){control=document.createElement(field.isMultiline()?'textarea':'input');control.value=field.getText()||'';if(field.isPassword())control.type='password';if(field.getMaxLength())control.maxLength=field.getMaxLength()}
else if(kind==='checkbox'){control=document.createElement('input');control.type='checkbox';control.checked=field.isChecked()}
else{control=document.createElement('select');const multi=kind==='list'||kind==='dropdown'?field.isMultiselect():false;control.multiple=multi;const selected=kind==='radio'?[field.getSelected()]:field.getSelected();if(!multi){const blank=document.createElement('option');blank.value='';blank.textContent='— ไม่เลือก —';control.append(blank)}for(const value of field.getOptions()){const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=selected.includes(value);control.append(option)}}
control.id=label.htmlFor;control.required=field.isRequired();control.disabled=field.isReadOnly();row.append(label,control);$('formFields').append(row);formEntries.push({name:field.getName(),kind,control,readOnly:field.isReadOnly(),required:field.isRequired()})});formData=data;formName=f.name;$('formStatus').textContent=fields.length?`พบ ${formEntries.length} ช่องที่รองรับ${unsupported?` · ข้าม ${unsupported} ช่องที่ยังไม่รองรับ เช่น ลายเซ็นดิจิทัล`:''}`:'ไฟล์นี้ไม่มีช่องฟอร์ม ใช้เครื่องมือเพิ่มข้อความเพื่อกรอกทับบนเอกสารได้';}catch(e){$('formStatus').textContent=/encrypt|password/i.test(e.message)?'กรุณาปลดล็อก PDF ก่อนเปิด':e.message}finally{lockForm(false)}};
$('saveForm').onclick=async()=>{if(!formData||formWorking)return;const values=[];for(const e of formEntries){if(e.readOnly)continue;let value=e.kind==='checkbox'?e.control.checked:e.kind==='text'?e.control.value:e.control.multiple?Array.from(e.control.selectedOptions,o=>o.value):e.control.value?[e.control.value]:[];if(e.required&&(!value||(Array.isArray(value)&&!value.length))){$('formStatus').textContent='กรุณากรอกช่องที่จำเป็น: '+e.name;e.control.focus();return}values.push({name:e.name,value})}lockForm(true);try{$('formStatus').textContent='กำลังบันทึกฟอร์ม…';const doc=await PDFLib.PDFDocument.load(formData,{updateMetadata:false});const response=await fetch('vendor/NotoSansThai.ttf');if(!response.ok)throw Error('โหลดฟอนต์ไม่สำเร็จ โปรดลองใหม่');const data=await PDFFeatures.fillFields(doc,values,PDFLib,fontkit,new Uint8Array(await response.arrayBuffer()));const url=URL.createObjectURL(new Blob([data],{type:'application/pdf'}));formUrls.push(url);$('formResults').replaceChildren();const link=document.createElement('a');link.href=url;link.download=formName.replace(/\.pdf$/i,'')+'-filled.pdf';link.textContent='↓ ดาวน์โหลดฟอร์มที่กรอกแล้ว';link.className='result-link';$('formResults').append(link);link.click();$('formStatus').textContent='บันทึกแล้ว ช่องฟอร์มยังแก้ไขต่อได้ในโปรแกรมอ่าน PDF'}catch(e){console.error(e);$('formStatus').textContent=e.message||'บันทึกไม่สำเร็จ'}finally{lockForm(false)}};
