'use strict';
let originalEnginePromise=null,originalFontPromise=null;
function loadOriginalEngine(){if(!originalEnginePromise)originalEnginePromise=(async()=>{const {init}=await import('./vendor/pdfium/pdfium.mjs');const response=await fetch('vendor/pdfium/pdfium.wasm');if(!response.ok)throw Error('โหลดเครื่องมือแก้ข้อความไม่สำเร็จ');const engine=await init({wasmBinary:await response.arrayBuffer()});engine.PDFiumExt_Init();return engine})().catch(e=>{originalEnginePromise=null;throw e});return originalEnginePromise}
function originalFont(){if(!originalFontPromise)originalFontPromise=fetch('vendor/NotoSansThai.ttf').then(r=>{if(!r.ok)throw Error('โหลดฟอนต์ไทยไม่ได้');return r.arrayBuffer()}).then(b=>new Uint8Array(b)).catch(e=>{originalFontPromise=null;throw e});return originalFontPromise}
const originalDialog=document.createElement('dialog');originalDialog.id='originalDialog';originalDialog.innerHTML='<div class="original-header"><div><span class="eyebrow">PDF STUDIO / TEXT EDITOR</span><h2>แก้ข้อความต้นฉบับ <small>รุ่นเริ่มต้น</small></h2></div><button id="closeOriginal" aria-label="ปิด">×</button></div><p class="original-note">เลือกกรอบข้อความแนวนอนเพื่อแก้ไข ข้อความเดิมจะถูกลบจริง ใช้ฟอนต์ทดแทน Noto Sans Thai และลดขนาดให้พอดีกรอบเดิมเมื่อจำเป็น • ไม่รองรับไฟล์สแกน ข้อความหมุน และข้อความที่อยู่ในวัตถุซ้อน</p><div class="original-toolbar"><label class="original-upload" for="originalFile">＋ เปิด PDF</label><input id="originalFile" type="file" accept="application/pdf,.pdf" hidden><button id="originalPrev" disabled>←</button><span id="originalPage">ยังไม่มีเอกสาร</span><button id="originalNext" disabled>→</button><button id="originalUndo" disabled>↶ เลิกทำ</button><button id="originalDownload" class="primary" disabled>↓ ดาวน์โหลด PDF</button></div><p id="originalStatus" role="status" aria-live="polite">เปิด PDF แล้วคลิกข้อความที่ต้องการแก้</p><div class="original-layout"><div id="originalSurface"><div id="originalPaper"><canvas id="originalCanvas" hidden></canvas><div id="originalBoxes"></div></div><p id="originalEmpty">เอกสารจะแสดงที่นี่</p></div><div class="original-fields"><label for="originalOld">ข้อความเดิม</label><textarea id="originalOld" readonly rows="3"></textarea><label for="originalNew">ข้อความใหม่ (บรรทัดเดียว)</label><input id="originalNew" maxlength="2000" disabled><button id="originalApply" class="primary" disabled>ใช้ข้อความใหม่</button><p id="originalSelectionHint">เลือกข้อความบนหน้า หรือจากรายการด้านล่าง • เว้นว่างเพื่อลบข้อความ</p><div id="originalList"></div></div></div>';
document.body.append(originalDialog);
let originalSource=null,originalOutput=null,originalFilename='',originalPageIndex=0,originalPageCount=0,originalItems=[],originalSelected=null,originalEdits=new Map(),originalHistory=[],originalWorking=false,originalPdf=null,originalViewport=null,originalUrl=null;
function openOriginalTool(){originalDialog.showModal()}
function originalMessage(text){$('originalStatus').textContent=text}
function originalControls(){const loaded=!!originalSource;$('originalFile').disabled=originalWorking;$('closeOriginal').disabled=originalWorking;$('originalPrev').disabled=originalWorking||!loaded||originalPageIndex===0;$('originalNext').disabled=originalWorking||!loaded||originalPageIndex+1>=originalPageCount;$('originalUndo').disabled=originalWorking||!originalHistory.length;$('originalDownload').disabled=originalWorking||!originalEdits.size;$('originalApply').disabled=originalWorking||!originalSelected;$('originalNew').disabled=originalWorking||!originalSelected;$('originalPage').textContent=loaded?`หน้า ${originalPageIndex+1} / ${originalPageCount}`:'ยังไม่มีเอกสาร';originalDialog.querySelectorAll('.original-pick').forEach(b=>b.disabled=originalWorking)}
function closeOriginal(){if(originalWorking)return;originalDialog.close()}
$('closeOriginal').onclick=closeOriginal;originalDialog.addEventListener('cancel',e=>{if(originalWorking)e.preventDefault()});
function originalKey(item){return item.page+':'+item.index}
function selectOriginal(item){if(originalWorking)return;originalSelected=item;$('originalOld').value=item.text;$('originalNew').value=originalEdits.get(originalKey(item))?.text??item.text;originalControls();originalDialog.querySelectorAll('.original-pick').forEach(b=>b.classList.toggle('selected',b.dataset.key===originalKey(item)));$('originalNew').focus()}
function drawOriginalChoices(){const boxes=$('originalBoxes'),list=$('originalList');boxes.replaceChildren();list.replaceChildren();for(const item of originalItems){const key=originalKey(item);const rect=originalViewport.convertToViewportRectangle(item.bounds);const x=Math.min(rect[0],rect[2]),y=Math.min(rect[1],rect[3]),w=Math.abs(rect[2]-rect[0]),h=Math.abs(rect[3]-rect[1]);const b=document.createElement('button');b.className='original-pick original-box';b.dataset.key=key;b.title=item.text;b.setAttribute('aria-label','แก้ข้อความ: '+item.text);b.style.left=x/originalViewport.width*100+'%';b.style.top=y/originalViewport.height*100+'%';b.style.width=w/originalViewport.width*100+'%';b.style.height=Math.max(h,8)/originalViewport.height*100+'%';b.onclick=()=>selectOriginal(item);boxes.append(b);const entry=document.createElement('button');entry.className='original-pick original-entry';entry.dataset.key=key;entry.textContent=(originalEdits.has(key)?'✓ ':'')+(originalEdits.has(key)?(originalEdits.get(key).text||'(ลบข้อความแล้ว)'):item.text);entry.onclick=()=>selectOriginal(item);list.append(entry)}originalControls()}
async function renderOriginal(){if(originalPdf){await originalPdf.destroy();originalPdf=null}pdfjsLib.GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js';originalPdf=await pdfjsLib.getDocument({data:originalOutput.slice(),isEvalSupported:false}).promise;const page=await originalPdf.getPage(originalPageIndex+1);originalViewport=page.getViewport({scale:1.3});if(originalViewport.width*originalViewport.height>24e6)throw Error('หน้าเอกสารใหญ่เกินขนาดที่รองรับ');const canvas=$('originalCanvas');canvas.width=originalViewport.width;canvas.height=originalViewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport:originalViewport}).promise;canvas.hidden=false;$('originalEmpty').hidden=true;$('originalPaper').style.width=originalViewport.width+'px';drawOriginalChoices()}
async function readOriginalPage(){const engine=await loadOriginalEngine();const info=OriginalPDF.inspect(engine,originalSource,originalPageIndex);originalItems=info.items;originalPageCount=info.pageCount;originalSelected=null;$('originalOld').value='';$('originalNew').value='';await renderOriginal();originalMessage(info.items.length?`เลือกแก้ได้ ${info.items.length} กลุ่มข้อความ${info.skipped?` · ข้าม ${info.skipped} วัตถุที่ยังไม่รองรับ`:''} · เปลี่ยนแล้ว ${originalEdits.size} กลุ่ม`:info.rotation?'หน้านี้มีการหมุน ยังไม่รองรับการแก้ข้อความ':'ไม่พบข้อความที่แก้ได้ในหน้านี้ อาจเป็นภาพสแกนหรือข้อความในวัตถุซ้อน')}
$('originalFile').onchange=async e=>{const file=e.target.files[0];if(!file||originalWorking)return;if(file.size>50*1024*1024){originalMessage('รองรับไฟล์ไม่เกิน 50 MB');return}if(originalEdits.size&&!confirm('เปิดไฟล์ใหม่และทิ้งการแก้ไขที่ยังไม่ได้ดาวน์โหลดหรือไม่?'))return;originalWorking=true;originalControls();originalMessage('กำลังโหลดเครื่องมือและอ่านข้อความ…');try{const data=new Uint8Array(await file.arrayBuffer());const check=await PDFLib.PDFDocument.load(data,{updateMetadata:false});if(check.isEncrypted)throw Error('กรุณาปลดล็อกไฟล์ก่อน');await loadOriginalEngine();originalSource=data;originalOutput=data.slice();originalFilename=file.name;originalPageIndex=0;originalEdits=new Map();originalHistory=[];await readOriginalPage()}catch(e){console.error(e);originalSource=null;originalOutput=null;originalSelected=null;originalItems=[];originalEdits=new Map();originalHistory=[];originalPageCount=0;$('originalBoxes').replaceChildren();$('originalList').replaceChildren();$('originalCanvas').hidden=true;$('originalEmpty').hidden=false;originalMessage(e.message||'เปิดไฟล์ไม่สำเร็จ')}finally{originalWorking=false;$('originalFile').value='';originalControls()}};
async function navigateOriginal(delta){if(originalWorking||!originalSource)return;const next=originalPageIndex+delta;if(next<0||next>=originalPageCount)return;originalWorking=true;originalControls();originalPageIndex=next;try{await readOriginalPage()}catch(e){originalMessage(e.message)}finally{originalWorking=false;originalControls()}}
$('originalPrev').onclick=()=>navigateOriginal(-1);$('originalNext').onclick=()=>navigateOriginal(1);
async function buildOriginal(edits){if(!edits.size)return originalSource.slice();return OriginalPDF.replace(await loadOriginalEngine(),originalSource,Array.from(edits.values()),PDFLib,fontkit,await originalFont())}
$('originalApply').onclick=async()=>{if(originalWorking||!originalSelected)return;const item=originalSelected,newText=$('originalNew').value;const next=new Map(originalEdits);if(newText===item.text)next.delete(originalKey(item));else next.set(originalKey(item),{page:item.page,index:item.index,original:item.text,text:newText});originalWorking=true;originalControls();originalMessage('กำลังแทนที่ข้อความเดิมและสร้างตัวอย่าง…');try{const data=await buildOriginal(next);originalHistory.push(new Map(originalEdits));if(originalHistory.length>30)originalHistory.shift();originalEdits=next;originalOutput=data;await renderOriginal();originalMessage(`แสดงผลหลังแก้ไขแล้ว · เปลี่ยน ${originalEdits.size} กลุ่มข้อความ · ตรวจตัวอย่างก่อนดาวน์โหลด`)}catch(e){console.error(e);originalMessage(e.message||'แก้ข้อความไม่สำเร็จ')}finally{originalWorking=false;originalControls()}};
$('originalUndo').onclick=async()=>{if(originalWorking||!originalHistory.length)return;originalWorking=true;originalControls();try{const next=originalHistory[originalHistory.length-1];const data=await buildOriginal(next);originalHistory.pop();originalEdits=new Map(next);originalOutput=data;originalSelected=null;$('originalOld').value='';$('originalNew').value='';await renderOriginal();originalMessage('เลิกทำแล้ว')}catch(e){originalMessage(e.message)}finally{originalWorking=false;originalControls()}};
$('originalDownload').onclick=()=>{if(originalWorking||!originalOutput||!originalEdits.size)return;if(originalUrl)URL.revokeObjectURL(originalUrl);originalUrl=URL.createObjectURL(new Blob([originalOutput],{type:'application/pdf'}));const a=document.createElement('a');a.href=originalUrl;a.download=originalFilename.replace(/\.pdf$/i,'')+'-text-edited.pdf';a.click();originalMessage('ดาวน์โหลด PDF ที่แก้ข้อความต้นฉบับแล้ว')};
window.addEventListener('beforeunload',e=>{if(originalEdits.size){e.preventDefault();e.returnValue=''}});
