/* PDFium removes the original text object; pdf-lib writes searchable replacement text. */
(function(root){
function openDocument(engine,data){const m=engine.pdfium,ptr=m.wasmExports.malloc(data.length);if(!ptr)throw Error('หน่วยความจำไม่พอ');m.HEAPU8.set(data,ptr);const doc=engine.FPDF_LoadMemDocument(ptr,data.length,'');if(!doc){m.wasmExports.free(ptr);throw Error('เปิด PDF ไม่ได้ หรือไฟล์มีรหัสผ่าน')}return{doc,close(){engine.FPDF_CloseDocument(doc);m.wasmExports.free(ptr)}}}
function inspectPage(engine,doc,index){const m=engine.pdfium,page=engine.FPDF_LoadPage(doc,index);if(!page)throw Error('อ่านหน้า PDF ไม่ได้');let textPage=0,scratch=0;try{const rotation=engine.FPDFPage_GetRotation(page);textPage=engine.FPDFText_LoadPage(page);if(!textPage)throw Error('อ่านข้อความไม่ได้');scratch=m.wasmExports.malloc(80);const items=[];let skipped=0;for(let i=0;i<engine.FPDFPage_CountObjects(page);i++){const object=engine.FPDFPage_GetObject(page,i),type=engine.FPDFPageObj_GetType(object);if(type===5){skipped++;continue}if(type!==1)continue;const n=engine.FPDFTextObj_GetText(object,textPage,0,0);if(n<2||n>200000){skipped++;continue}const str=m.wasmExports.malloc(n);let text;try{engine.FPDFTextObj_GetText(object,textPage,str,n);text=m.UTF16ToString(str)}finally{m.wasmExports.free(str)}if(!text.trim())continue;
if(!engine.FPDFPageObj_GetMatrix(object,scratch)||!engine.FPDFTextObj_GetFontSize(object,scratch+24)||!engine.FPDFPageObj_GetBounds(object,scratch+28,scratch+32,scratch+36,scratch+40)){skipped++;continue}
const matrix=Array.from(m.HEAPF32.subarray(scratch/4,scratch/4+6)),fontSize=m.HEAPF32[(scratch+24)/4]*matrix[3],bounds=Array.from(m.HEAPF32.subarray((scratch+28)/4,(scratch+44)/4));const clip=engine.FPDFPageObj_GetClipPath(object);const clipped=clip&&engine.FPDFClipPath_CountPaths(clip)>0;
if(rotation!==0||Math.abs(matrix[1])>.0001||Math.abs(matrix[2])>.0001||matrix[0]<=0||matrix[3]<=0||fontSize<1||fontSize>300||bounds[2]<=bounds[0]||bounds[3]<=bounds[1]||/[\r\n\uFFFD]/.test(text)||engine.FPDFTextObj_GetTextRenderMode(object)!==0||clipped){skipped++;continue}
let color=[0,0,0,1];if(engine.FPDFPageObj_GetFillColor(object,scratch+44,scratch+48,scratch+52,scratch+56))color=Array.from(m.HEAPU32.subarray((scratch+44)/4,(scratch+60)/4),v=>v/255);if(color[3]===0){skipped++;continue}items.push({page:index,index:i,text,matrix,fontSize,bounds,color})}
return{items,skipped,rotation};}finally{if(scratch)m.wasmExports.free(scratch);if(textPage)engine.FPDFText_ClosePage(textPage);engine.FPDF_ClosePage(page)}}
function inspect(engine,data,pageIndex){const opened=openDocument(engine,data);try{const count=engine.FPDF_GetPageCount(opened.doc);if(!Number.isInteger(pageIndex)||pageIndex<0||pageIndex>=count)throw Error('เลขหน้าไม่ถูกต้อง');return{...inspectPage(engine,opened.doc,pageIndex),pageCount:count}}finally{opened.close()}}
function serialize(engine,doc){const m=engine.pdfium,writer=engine.PDFiumExt_OpenFileWriter();let ptr=0;try{if(!engine.FPDF_SaveAsCopy(doc,writer,2))throw Error('บันทึกเนื้อหา PDF ไม่สำเร็จ');const size=engine.PDFiumExt_GetFileWriterSize(writer);if(size<=0)throw Error('ไฟล์ผลลัพธ์ว่าง');ptr=m.wasmExports.malloc(size);if(engine.PDFiumExt_GetFileWriterData(writer,ptr,size)!==size)throw Error('อ่านไฟล์ผลลัพธ์ไม่สำเร็จ');return m.HEAPU8.slice(ptr,ptr+size)}finally{if(ptr)m.wasmExports.free(ptr);engine.PDFiumExt_CloseFileWriter(writer)}}
async function replace(engine,source,edits,lib,fontkit,fontBytes){if(!edits.length)return source.slice();const keys=new Set(),opened=openDocument(engine,source);let removed,prepared=[];try{const byPage=new Map();for(const edit of edits){if(typeof edit.text!=='string'||/[\r\n]/.test(edit.text)||edit.text.length>2000)throw Error('รองรับข้อความบรรทัดเดียว ไม่เกิน 2,000 ตัวอักษร');const key=edit.page+':'+edit.index;if(keys.has(key))throw Error('รายการแก้ไขซ้ำ');keys.add(key);if(!byPage.has(edit.page))byPage.set(edit.page,[]);byPage.get(edit.page).push(edit)}for(const [pageIndex,changes] of byPage){if(!Number.isInteger(pageIndex)||pageIndex<0||pageIndex>=engine.FPDF_GetPageCount(opened.doc))throw Error('เลขหน้าไม่ถูกต้อง');const available=inspectPage(engine,opened.doc,pageIndex).items;for(const change of changes){const item=available.find(i=>i.index===change.index);if(!item||item.text!==change.original)throw Error('ข้อความต้นฉบับเปลี่ยนไป กรุณาเปิดไฟล์ใหม่');prepared.push({...item,replacement:change.text})}}
// Validate font coverage and fit before changing the original objects.
const fontDoc=await lib.PDFDocument.create();fontDoc.registerFontkit(fontkit);const measureFont=await fontDoc.embedFont(fontBytes,{subset:true});const charset=new Set(measureFont.getCharacterSet());for(const item of prepared){if(Array.from(item.replacement).some(c=>!charset.has(c.codePointAt(0))))throw Error('ฟอนต์ทดแทนยังไม่รองรับบางตัวอักษร ใช้ภาษาไทย อังกฤษ และตัวเลข');const width=measureFont.widthOfTextAtSize(item.replacement,item.fontSize);item.size=width?Math.min(item.fontSize,item.fontSize*(item.bounds[2]-item.bounds[0])/width):item.fontSize;if(item.size<4)throw Error('ข้อความใหม่ยาวเกินกรอบ กรุณาย่อข้อความ');}
for(const [pageIndex,changes] of byPage){const page=engine.FPDF_LoadPage(opened.doc,pageIndex);try{for(const edit of changes.slice().sort((a,b)=>b.index-a.index)){const object=engine.FPDFPage_GetObject(page,edit.index);if(!engine.FPDFPage_RemoveObject(page,object))throw Error('ลบข้อความเดิมไม่สำเร็จ');engine.FPDFPageObj_Destroy(object)}if(!engine.FPDFPage_GenerateContent(page))throw Error('สร้างเนื้อหาหน้าใหม่ไม่สำเร็จ')}finally{engine.FPDF_ClosePage(page)}}removed=serialize(engine,opened.doc);}finally{opened.close()}
const doc=await lib.PDFDocument.load(removed,{updateMetadata:false});doc.registerFontkit(fontkit);const font=await doc.embedFont(fontBytes,{subset:true});for(const item of prepared){if(!item.replacement)continue;doc.getPage(item.page).drawText(item.replacement,{x:item.matrix[4],y:item.matrix[5],size:item.size,font,color:lib.rgb(...item.color.slice(0,3)),opacity:item.color[3]})}return doc.save({updateFieldAppearances:false,useObjectStreams:true});}
root.OriginalPDF={inspect,replace};if(typeof module!=='undefined')module.exports=root.OriginalPDF;
})(globalThis);
